### ISSUE TITLE
Vuex/Typescript mappers issue: property does not exist on type 'CombinedVueInstance<Vue, ...>'

### ISSUE THREAD

**Issue by mzymta** [vuejs/vuex#1220] opened 2018-04-09 16:28 UTC
### Version
3.0.1

### Reproduction link
[https://github.com/mzymta/vuex-mappers-issue](https://github.com/mzymta/vuex-mappers-issue)

### Steps to reproduce
Add mapped methods using mapMutations, mapActions, create another component method that uses any of the mapped methods. Build fails with error:
> Error: Property NAME_OF_MAPPED_METHOD does not exist on type 'CombinedVueInstance<Vue, ...>'

The below code works fine if there is no methodThatUsesActionOrMutation() method.
With methodThatUsesActionOrMutation() method build fails with error:
>TS2339: Property 'pushStringArray' does not exist on type 'CombinedVueInstance<Vue, {}, { methodThatUsesActionOrMutation(): void; }, { newStr: any; getLongS...'.

```
import Vue from 'vue';
import {mapActions, mapGetters, mapMutations} from 'vuex'

export default Vue.extend({
  computed: {
    ...mapGetters({
      getStringsArray: 'getStringsArray'
    }),
    newStr: {
      get(): string {
        return this.$store.state.newStr;
      },
      set(value: string) {
        this.$store.commit('setNewStr', value);
      }
    }
  },
  methods: {
    ...mapMutations({
      pushStringArray: 'pushStringArray'
    }),
    ...mapActions({
      pushStringArrayAsync: 'pushStringArrayAsync'
    }),
    methodThatUsesActionOrMutation() {
      // HERE COMES THE ERROR
      this.pushStringArray();
      console.log('done');
    }
  }
}
```

### What is expected?
mapped method pushStringArray() can be used in other component methods - build doesn't fail

### What is actually happening?
Build fails with error:
TS2339: Property 'pushStringArray' does not exist on type 'CombinedVueInstance<Vue, {}, { methodThatUsesActionOrMutation(): void; }, { newStr: any; }, Reado...'.

**Comment by ktsn** [comment] 2018-04-10 00:16
Duplicate of #1119 
Fix is going on #1121

**Closed by ktsn** 2018-04-10 00:16 UTC

**Comment by JWong1105** [comment] 2019-04-25 03:05
I donot know yet~ And I have got a seem problem, but not Typescript, just a normal Vuex project with vscode, the red errors only appear in template tags...

**Comment by sknightq** [comment] 2019-04-25 06:43
> I donot know yet~ And I have got a seem problem, but not Typescript, just a normal Vuex project with vscode, the red errors only appear in template tags...

Me too!

**Comment by pikax** [comment] 2019-04-25 06:53
@JWong1105 vscode uses the typescript typings from the dependencies when using javascript

**Comment by 1316636084** [comment] 2019-04-26 05:14
how to fix it

**Comment by lihaowu** [comment] 2019-04-26 08:59
昨天VSCode大批量更新，去掉报错的办法，File->Proferences->Extensions->Vetur->Validation:Template , Cancel it.

**Comment by Aslantoe** [comment] 2019-04-27 01:53
reload一下Vetur好了

**Comment by floait** [comment] 2019-04-29 00:43
reload the plugin `Vetur`, opening the new world!!!!!!

**Comment by rikakomoe** [comment] 2019-11-09 07:34
Any update here? I've facing the same issue.

**Comment by DanielRuf** [comment] 2019-12-11 17:09
We still face this issue, even with the latest version / release.

**Comment by DanielRuf** [comment] 2019-12-11 17:09
We use mapGetters.

**Comment by xesjkeee** [comment] 2020-03-09 20:59
I still face this issue using `mapMutations`

**Comment by SanyaShevchuk** [comment] 2020-03-11 21:49
still face this problem with mapState, mapMutations etc. It can be reproduced if we have our component's computed/methods and vuex such as:
```
computed: {
  myProperty() {
     return true
  },
  ...mapState('someModule', ['someStateField'])
}
```

**Comment by kiaking** [comment] 2020-03-12 03:00
@SanyaShevchuk Could you try annotating the other properties? (Computed methods require return value annotation).

```ts
computed: {
  myProperty(): boolean {
     return true
  },
  ...mapState('someModule', ['someStateField'])
}
```

**Comment by pablo-iwg** [comment] 2020-04-21 02:19
The above fixed the issue for me. @kiaking thank you!

**Comment by SanyaShevchuk** [comment] 2020-04-22 21:12
yes I tried, it works for mapState and mapGetters, but does not for mapMutations. Ive added return type to methods as u did for computed, but still get an error

**Comment by SanyaShevchuk** [comment] 2020-04-22 21:18
@pablo-iwg did u have a case with mutations or only computed?

**Comment by pablo-iwg** [comment] 2020-04-22 22:35
I was using getters within a computed property and forgot to annotate the property. I was not using mutations.

**Comment by SanyaShevchuk** [comment] 2020-04-23 07:04
Ive added return type for everything either computed or method but still mapMutations gets error

**Comment by jQrgen** [comment] 2020-05-09 14:25
+1

**Comment by Smilebags** [comment] 2020-06-12 02:12
I'm also only experiencing this with mapMutations, all getters and method return values are typed.

**Comment by blaskovicz** [comment] 2022-10-19 14:04
Is there currently an open issue for this? I'm still seeing this for `...mapState()`

**Comment by JWong1105** [comment] 2022-10-19 14:05
您的邮件我已收到！祝您天天好心情~王杰

**Comment by fbnlsr** [comment] 2023-06-29 10:24
Just chiming in that I also get this issue, but only when `mapState()` is present alongside others methods:

```js
computed: {
      ...mapState(['user']),
      acquereurName(): string {
        return this.item.acquereur?.formName ?? ''
      },
    },
```

Here I get `Property 'user' does not exist on type 'Property 'user' does not exist on type 'CombinedVueInstance<Vue, { minPosition: number; busy: boolean; itemData: RequisitionItem; rubriques: never[]; stockStatuses: { label: string; value: string; color: string; textColor: string; }[]; ... 30 more ...; showRegroupModal: boolean; }, { ...; }, { ...; }, Readonly<...>>'.Vetur(2339)`

But if my component only has this:

```js
computed: {
     ...mapState(['user']),
  },
```

...then there are no errors to report.
