### ISSUE TITLE
Support Set object in Vuex

### ISSUE THREAD

**Issue by ppasieka** [vuejs/vuex#1063] opened 2017-11-22 09:34 UTC
### What problem does this feature solve?
Set object are very useful in situations where uniqueness is required. In my opinion it is cleaner to use Set instead object literals with values set to `true`

```javascript

var state = {
  items: new Set()
}
var mutations = {
  newItem(state, item) {
    // state.items = { ...state.items, item: true }  // -- works but it is kinda hack
    // state.items = new Set([...state.items, item]) // -- this works correctly but is messy
    
    state.items.add(item) // -- it seems to not observe changes through add method.
  }
}
```
Link to sandbox with this example  https://codesandbox.io/s/03w04xjq4p

### What does the proposed API look like?
No extra API is needed. Observe changes through native Set methods `add` and `delete`

**Comment by ktsn** [comment] 2017-11-22 10:00
This is essentially duplicate of #439 and #471.
And there are nothing we can do for this in Vuex since it just use Vue's reactivity system.

**Closed by ktsn** 2017-11-22 10:00 UTC
