### ISSUE TITLE
Dynamic modules that use Namespaces need a way to check if they are already registered

### ISSUE THREAD

**Issue by erichorne** [vuejs/vuex#1300] opened 2018-06-09 16:21 UTC
### What problem does this feature solve?
When registering a dynamic module, an error can occur in the console warning that some attributes of the modules are duplicates if the namespace has already been registered. Having a way to check if the namespace path is already occupied would allow the code to either, register to a different namespace (ick!), unregister and re-register the existing namespace or avoid registration of the namespace altogether. 

This condition can be easily reproduced by dynamically registering a namespaced module and issuing a hotreload or attempting to register that module more than once to the same path. 

End users would not see errors on hot-load or, if for some reason, the code attempts multiple registrations in the same session.

The only workaround at this point is to check the private member _modulesNamespaceMap. Building a dependency on that private access isn't ideal. I can find no other way to determine if the namespace is already occupied. 

### What does the proposed API look like?
Option A: Provide a boolean method that returns the state of a given namespace:

    this.$store.isNamespaceRegistered("nested/name/space")

Option B: Exit from registerModule and provide a false return code from registerModule when the namespace already exists. 

    if (this.$store.registerModule("existing/namespace", myModule) === false) {
       this.$store.unregisterModule("existing/namespace")
       this.$store.registerModule("existing/namespace", myModule)
    }

I personally like Option A better as it is minimally intrusive on the existing API and gives the developer the means by which to handle the issue with the greatest flexibility.

**Comment by ktsn** [comment] 2018-06-15 01:03
Duplicate of #833

**Closed by ktsn** 2018-06-15 01:03 UTC
