### ISSUE TITLE
Memory leak on a trivial app

### ISSUE THREAD

**Issue by Kasheftin** [vuejs/vuex#1934] opened 2021-02-15 22:48 UTC
### Version
4.0.0

### Reproduction link
[https://kasheftin.github.io/vuex4-memory-leak-example2/](https://kasheftin.github.io/vuex4-memory-leak-example2/)

### Steps to reproduce
- Load the app and use chrome devtools memory tab;
- Take heap snapshot; The result is ~ 4.5 MB;
- Press "Add" button. It will create 100 items in the store;
- Take heap snapshot; The result is ~ 15.7 MB;
- Press "Clear regular items" button. It will remove all items in the store;
- Take heap snapshot; The result is still ~ 15.7 MB;
- Add/remove items multiple times, notice the allocated space grows all the time;

### What is expected?
There's exactly the same app for vue2.6   vuex3.4: https://kasheftin.github.io/vuex4-memory-leak-example1/
Exactly the same code gives the correct result there: memory is cleared up correctly there. It should be the same in vue3.0   vuex4.0.

### What is actually happening?
Allocated memory is not cleared up in vue3.0   vuex4.0

---
vue2.6   vuex3.4 source code (working correctly):

https://github.com/Kasheftin/vuex4-memory-leak-example1

vue3.0   vuex4.0 source code (memory leak):

https://github.com/Kasheftin/vuex4-memory-leak-example2

**Comment by Kasheftin** [comment] 2021-02-16 18:10
That's vuex4 issue. If I replace vuex with just a plain array in data, everything works as expected (no memory leak):
Example 3 (vue3 without vuex): https://kasheftin.github.io/vuex4-memory-leak-example3/
Source code: https://github.com/Kasheftin/vuex4-memory-leak-example3

**Comment by Trinovantes** [comment] 2021-04-29 02:22
![Screenshot 2021-04-28 221836](https://user-images.githubusercontent.com/458691/116494868-bff0d600-a86f-11eb-9fc3-26f7daffee89.png)

If I'm reading this right, it seems the memory leak is caused by Vue Devtools chrome extension retaining a reference to the array. If I delete the extension, I can't reproduce the memory leak in your example2 url.

**Comment by Kasheftin** [comment] 2021-04-29 06:42
Good catch!

**Comment by Akryum** [comment] 2021-04-29 08:14
Vuex 4 has outdated devtools code form Vuex 3.

#1949

**Comment by kiaking** [comment] 2021-06-01 15:38
This should be fixed on Vuex 4.0.1 with the correct new Devtools support 👍

**Closed by kiaking** 2021-06-01 15:38 UTC

**Comment by gdabs** [comment] 2021-08-31 07:56
i update vuex to version v4.0.2 but memory leak persist

**Comment by m00nk** [comment] 2021-09-26 02:43
I see the memory leaks in SSR (Quasar project). The leaks disappear when I disable vuex.

**Comment by stauren** [comment] 2021-11-24 07:57
also have the same memory leak issue in SSR using v4.0.2, please reopen this bug.

**Comment by gdabs** [comment] 2021-11-24 08:02
> also have the same memory leak issue in SSR using v4.0.2, please reopen this bug.

i have used createVuexStore in serverRender file to resolve this problem

**Comment by stauren** [comment] 2021-11-24 08:11
> > also have the same memory leak issue in SSR using v4.0.2, please reopen this bug.
> 
> i have used createVuexStore in serverRender file to resolve this problem

Can not find an API called createVuexStore. Where can find it?

**Comment by gdabs** [comment] 2021-11-24 08:15
> 

first, you should find where are your store established in, erery page should establish a unrelated strore

**Comment by stauren** [comment] 2021-11-24 08:24
> > 
> 
> first, you should find where are your store established in, erery page should establish a unrelated strore

In my case every SSR request create new vuex store, no store instance is reused, still have the leak. Think need an API to release or unload the Vuex instance.

**Comment by Carseason** [comment] 2022-01-12 08:36
> 

Using devtools: false solved the problem for me

**Comment by andoniabedul** [comment] 2022-10-17 12:00
Thank you @Carseason we solved a huge problem of memory leak thanks to your comment.
