### ISSUE TITLE
`createNamespacedHelpers` return mappers that need `this`

### ISSUE THREAD

**Issue by davidmeirlevy** [vuejs/vuex#1684] opened 2020-02-21 18:34 UTC
### Version
3.1.2

### Reproduction link
[https://jsfiddle.net/davidmeirlevy/9hbqjmg2/34/)

### Steps to reproduce
get a mapper:
`const { mapActions } = createNamespacedHelpers(MODULE_NAME)`

map some action:
`const {action} = mapActions(['action'])`

run this action directly, without adding it to a component methods:
`action()`

### What is expected?
the action should be dispacthed

### What is actually happening?
This line breaks because we didn't ran this function from a vue component context:
`var dispatch = this.$store.dispatch;`

---
when we want to use the mappers from the `setup()` function of the composition-api, the component's `this` shouldn't be relevant, so you should probably find another way to map actions without expecting being executed as a vue component's method.

**Comment by davidmeirlevy** [comment] 2020-02-24 06:46
Iv'e added a PR to fix this issue:
https://github.com/vuejs/vuex/pull/1685

After this fix, we can use the namespaced-helpers alongside with the composition-api.

**Comment by ktsn** [comment] 2020-02-25 16:55
We would not reuse `mapXXX` helpers for `setup` usage as they are totally different things and supporting both on one helper function will complicate the implementation. We are working on Vue v3 + Vuex now and considering `useXXX` composition function for `setup`.

**Comment by kiaking** [comment] 2020-02-26 00:53
Also it's not only for `createNamespacedHelpers`. All of the `mapXXX` features are meant be used inside Vue Component since they all tries to fetch store instance from the `this` context.

Let's close this one for now since it's indeed intended behavior, and if we want to have issue for `useXXX` feature, we should have it as a fresh issue 🤝

**Closed by kiaking** 2020-02-26 00:53 UTC

**Comment by davidmeirlevy** [comment] 2020-02-26 06:36
So basically you’re saying that “createNamespacedHelpers” is deprecated?

**Comment by kiaking** [comment] 2020-02-26 06:40
No. You can use all `mapXXX` helpers in Vue Component, but outside of `setup` hook. For `setup` hook, we probably have other helpers such as `useXXX` helpers.

**Comment by davidmeirlevy** [comment] 2020-02-26 07:02
There will be something such as “useNamespaced” ?

**Comment by kiaking** [comment] 2020-02-26 07:04
Probably. Not 100% sure just yet, but I guess something like that 👍

**Comment by davidmeirlevy** [comment] 2020-02-26 10:24
@kiaking Is my implementation looks good?
https://github.com/greenpress/vuex-composition-helpers

**Comment by kiaking** [comment] 2020-02-27 00:46
Yeah in terms of API, it looks good 👍 I think you don't have to pass `root.store` since you can fetch the store instance by `inject` hook inside the helper functions.

**Comment by davidmeirlevy** [comment] 2020-02-27 06:38
Interesting idea. Thanks.
