### ISSUE TITLE
[ssr] getters can't get data in client-side

### ISSUE THREAD

**Issue by dongnaebi** [vuejs/vuex#1229] opened 2018-04-13 09:30 UTC
### Version
3.0.1

### Steps to reproduce
I use Vuex module in vue-ssr,`this.$store.getters['product/screening']` in server-side is work,but in client-side is undefined,how can i solve this problem?or it's a bug?here's my code
```javascript
  import {mapState} from 'Vuex'
  import product from '~/store/modules/product'
  import 'vue-awesome/icons/map-marker-alt'
  export default {
    asyncData ({ store, route }) {
      store.registerModule('product', product)
      return store.dispatch('product/getProductList', {coll: '2', page: 1})
    },
    destroyed () {
      this.$store.unregisterModule('product')
    },
    data: () => ({
      
    }),
    computed: {
      ...mapState({
        list: state => state.product.productList.product,
      }),
      screening () {
        let screening = this.$store.getters['product/screening']
        console.log(screening) // server-side is work,client-side is undefined
        ...
        return screening
      }
    }
  }
```
```javascript
// product.js
import fetch from '../../api'
export default {
  namespaced: true,
  state: () => ({
    productList: null
  }),
  getters: {
    screening: state => {
      state.productList.screening.forEach(s => {
        s.value = [{id: 0, name: '全部'}].concat(s.value)
      })
      return state.productList.screening
    }
  },
  mutations: {
    setProductList (state, data) {
      state.productList = data
    }
  },
  actions: {
    async getProductList ({commit, dispatch, rootState}, params = {coll: '', keyword: '', productId: 0, page: 1}) {
      const res = await dispatch('handleError', await fetch(rootState, '/web/api/products/v1', params), { root: true })
      commit('setProductList', res.data)
    }
  }
}
```

### What is expected?
`this.$store.getters['product/screening']` do not undefined

### What is actually happening?
`this.$store.getters['product/screening']` return undefined

**Comment by ktsn** [comment] 2018-04-16 06:30
@dongnaebi 
Thanks for reporting this issue. Can you provide a minimal / self-contained reproduction?

**Comment by eeerrrttty** [comment] 2018-04-18 07:29
I think im with the same problem. Here, i was getting the getters, but when i started a query inside the query, getters couldn't reproduce nice.

here is my code that was updating properly:

`    loadPosts ({commit}) {
      commit('setLoading', true)
      firebase.firestore().collection('posts').orderBy('date', 'desc').limit(12).get()
        .then(function (querySnapshot) {
          let posts = []
          querySnapshot.forEach(function (doc) {
            // doc.data() is never undefined for query doc snapshots
            posts.push({
              id: doc.id,
              creatorName: doc.data().creatorName,
              creatorPhoto: doc.data().creatorPhoto,
              creatorId: doc.data().creatorId,
              date: doc.data().date,
              description: doc.data().description,
              imageUrl: doc.data().imageUrl
            })
          })
          commit('setLoadedPosts', posts)
          commit('setLoading', false)
        })
    },`

It was working very well.
Then i started to query the counters inside the posts:

`    loadPosts ({commit}) {
      commit('setLoading', true)
      firebase.firestore().collection('posts').orderBy('date', 'desc').limit(12).get()
        .then(function (querySnapshot) {
          let posts = []
          querySnapshot.forEach(function (doc) {
            // doc.data() is never undefined for query doc snapshots
            firebase.firestore().collection('posts').doc(doc.id).collection('postStatistics').doc('counters').get()
              .then((postCounters) => {
                posts.push({
                  id: doc.id,
                  creatorName: doc.data().creatorName,
                  creatorPhoto: doc.data().creatorPhoto,
                  creatorId: doc.data().creatorId,
                  date: doc.data().date,
                  description: doc.data().description,
                  imageUrl: doc.data().imageUrl,
                  evaluations: postCounters.data().evaluations,
                  rating: postCounters.data().rating,
                  total_commentaries: postCounters.data().total_commentaries,
                  visualizations: postCounters.data().visualizations
                })
              })
          })
          commit('setLoadedPosts', posts)
          commit('setLoading', false)
        })
    },`

![bug](https://user-images.githubusercontent.com/19417947/38917356-95abc7b2-42b8-11e8-9e5b-bbc5dc060029.png)

as you can see, state shows '0 loaded posts', but user is getting the view, console also shows right.
But this get complicated as i move to 'loadMorePosts' function (infinity scroll), it gets the bug and then turns into a mess

**Comment by ktsn** [comment] 2018-04-18 07:44
Snippets and screenshot is not a valid reproduction because we cannot actually confirm the problem by them.
You can use [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io/) or github repo to make a reproduction.

**Comment by eeerrrttty** [comment] 2018-04-22 03:45
@ktsn, this error require having a collection of 'post' with a sub-collection in each document of 'postCounters', this is running in production with firestore, how can i reproduce this?

**Comment by eeerrrttty** [comment] 2018-04-22 03:46
Also, this by itself is a bug, im returning the posts from 'loadedPosts' array, it is showing [0], which is incosistent with the result

**Comment by ktsn** [comment] 2018-04-22 05:56
Please try to boil down the problem and eliminate extra dependencies from repro. See the description about the reproduction in vue-issue-helper. http://new-issue.vuejs.org/?repo=vuejs/vuex

**Comment by Penggggg** [comment] 2018-06-06 09:48
- egg: 2.8.1
- vue: 2.5.16,
- vuex: 3.0.1
- vue-server-renderer: 2.5.16

> What happen

I meet the same problem in **vue srr** that I can't get my actions、getters、mutations in **client side**, but it is work in **asyncData** function in **server side**.
**[vuex] unknown action type** will show in client side

> hope

I hope I can get  actions、getters、mutations in any life curcul just like ``mounted( )``

> code 

```
// store/index.js

const actions = {
    [Types.FETCH_DIC_LIKE_LABEL]({ commit, dispatch, state }) {
        return http({
            url: '/api/likehall/dic/like-labels',
        });
    },
};

const state = {
    likeLables: [ ],
};

export default ({
    actions,
    getters: { },
    mutations: { },
    namespaced: true,
    state: ( ) => state,
});
```

```
// index.vue
<script>
export default {
   asyncData({ store }) {
        return store.registerModule( 'likeHall', likeHallStore );
    }
}
</script>
```

```
// other.vue
<script>
export default {
   mounted( ) {
        this.$store.dispatch(`likeHall/FETCH_DIC_LIKE_LABEL`);
        // error: [vuex] unknown action type: likeHall/FETCH_DIC_LIKE_LABEL
   }
}
</script>
```

**Comment by ktsn** [comment] 2018-06-15 01:42
Closing as reproduction is not provided in a long time. Please open a new issue if you can follow up some information.

**Closed by ktsn** 2018-06-15 01:42 UTC
Labels: need repro

**Comment by 960590968** [comment] 2018-09-06 06:12
how to resovle this error?  I hava too。

**Comment by NuxTijNhaX** [comment] 2023-05-18 08:39
I met this problem. :((((
Please help me resolve it.
