### ISSUE TITLE
Vuex triggers the 'updated' hook when a completely unrelated dynamic module is being registered

### ISSUE THREAD

**Issue by chetzof** [vuejs/vuex#1165] opened 2018-02-26 13:39 UTC
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/132227/](https://jsfiddle.net/50wL7mdz/132227/)

### Steps to reproduce
No steps to reproduce.
Just open the jsfiddle, you will see an alert that is called by the updated() hook. 

### What is expected?
The alert should not be displayed  because the registration of a new unrelated dynamic module should not trigger anything anywhere that is has no connection to.

### What is actually happening?
The component triggers updated() hook when dynamically registering an unrelated module

**Comment by ktsn** [comment] 2018-02-26 14:58
This is expected behavior. Because it adds the new value `state.b`, then `state` is marked as updated value, then the instance that is using `state` in its computed property `stateFoo` is updated. If you don't mutate root state, the update will not occur. https://jsfiddle.net/50wL7mdz/132513/

In any cases, you should report such topic into https://github.com/vuejs since this is related with Vue's reactivity system.

**Closed by ktsn** 2018-02-26 14:58 UTC
