### ISSUE TITLE
registerModule does not warn if existing state is overwritten

### ISSUE THREAD

**Issue by winniehell** [vuejs/vuex#1566] opened 2019-06-07 19:43 UTC
### Version
3.1.1

### Reproduction link

[https://jsfiddle.net/winniehell/enjkob2w/](https://jsfiddle.net/winniehell/enjkob2w/)

### Steps to reproduce
- create store module with some state
- dynamically register module with same name but different state

### What is expected?
a warning or error is shown

### What is actually happening?
state is silently overwritten

---
This issue is similar to https://github.com/vuejs/vuex/issues/1363.

**Comment by hybridwebdev** [comment] 2019-06-23 02:12
I think if people are registering modules, they know the shape of the state their extending with their module. No need to hold their hands when they should know what the results of their code will be.

**Comment by ktsn** [comment] 2019-11-10 14:39
Duplicate of #1363

**Closed by ktsn** 2019-11-10 14:39 UTC
