### ISSUE TITLE
Reactivity trigger on store.registerModule

### ISSUE THREAD

**Issue by vks-financial-com** [vuejs/vuex#1765] opened 2020-06-02 14:23 UTC
### Version
3.4.0

### Reproduction link
[https://codesandbox.io/s/vuex-dynamic-module-re-render-kju2b](https://codesandbox.io/s/vuex-dynamic-module-re-render-kju2b)

### Steps to reproduce
1. Initialize store
2. Add/register a module "x"
3. Register module "y1" within module "x". Module "y1" should contain a property "z" in its state
4. Create a computed property "c" in the app, which returns an object containing property "z" from module "y1" state
5. Create a watcher "w" for the computed property "c" with a logging function
6. Register module "y2" within module "x"
7. Observe watcher "w" being triggered

Reproduction is best described by the code in the provided test-case

### What is expected?
There should be no triggered getter reactivity for the properties in the state of a vuex module after a sibling module has been registered

### What is actually happening?
Upon registering a vuex module, getters for properties in the state of already registered sibling vuex modules are being triggered

---
Computed properties in the app, which do complex computations with values coming from the vuex modules, are being unnecessarily reexecuted on vuex module registration, substantially slowing down a complex application

**Comment by abellion** [comment] 2020-06-03 09:40
Same issue here !

**Comment by kiaking** [comment] 2020-06-08 08:46
Yes, this is expected behavior for now. Please see [this comment](https://github.com/vuejs/vuex/issues/1593#issuecomment-578116958).

We should be tackling this issue in Vuex 5! I'll close this issue since it's duplicate of #1593.

**Closed by kiaking** 2020-06-08 08:46 UTC
