### ISSUE TITLE
A watch option in Vuex store definitions for defining watchers like the Vue component definition watch option

### ISSUE THREAD

**Issue by tomknappramos** [vuejs/vuex#1951] opened 2021-03-21 13:33 UTC
### What problem does this feature solve?
The end user experience is a significantly more approachable and developer-friendly way to utilize watchers in Vuex.

To me, this has always just seemed like "the missing piece of Vuex". 

What I mean by "missing piece of Vuex" can perhaps be made more clear with the following analogy,  
component definition :: store definition  
data :: state  
computed :: getters  
methods :: actions  
watch :: ???  

I know there is a root instance-level store.watch() method in Vuex, but I'm not talking about that, so thanks in advanced for not just replying with that and just closing this. I'm sure I'm not the only person who has thought this.

Perhaps there is a very valid reason as to why this isn't part of Vuex? Is the sole reason to "keep the API surface small"? Or are there perhaps technical reasons why this can't be a thing?  

Again, I'm simply just asking "why".

Thanks!  
Vue/Vuex is the best!

### What does the proposed API look like?
```js
import api from '@/api'

const store = new Vuex.Store({
  state: {
    count: 0
  },
  getters: {
    countIsMultipleOf10: function(state) {
      return (state.count % 10 == 0)
    },
  },
  mutations: {
    increment: function(state) {
      state.count  
    }
  },
  watch: {
    'state.count': async function({ state, getters, commit, dispatch }, val, oldVal) {
      await api.updateSomething()
      console.log('Something was updated')
    },
    'getters.countIsMultipleOf10': async function({ state, getters, commit, dispatch }, val, oldVal) {
      await api.updateSomethingElse()
      console.log('Something else was updated')
    }
  },
})
```

**Comment by cuebit** [comment] 2021-03-21 21:59
Duplicate of #1219

Please create issues if you've found an actual issue or wish to propose a new feature. Questions can asked and answered in the [Discord](https://chat.vuejs.org/). Thanks!

**Closed by cuebit** 2021-03-21 21:59 UTC
