### ISSUE TITLE
getters result doesn't get cached

### ISSUE THREAD

**Issue by BoHuny** [vuejs/vuex#2102] opened 2021-12-30 16:55 UTC
### Version
4.0.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/admiring-swartz-hcbh5?file=/src/main.js)

### Steps to reproduce
- Instanciate a Vuex store
- Call a getter multiple times without change in the parameters
- The getter gets called each time as the result isn't cached

### What is expected?
The getter function should be computed once only (as in this Vue 2 minimal reproduction: https://codesandbox.io/s/interesting-cerf-22fu3?file=/src/main.js)

### What is actually happening?
The getter function is called each time

---
Vue version: 3.2.26 (doesn't work on 3.1.5/3.0.11 neither)

**Comment by kyrsquir** [comment] 2022-01-04 05:58
Glad we are not the only ones facing this, we started to think that nobody else use getters with Vuex 4.


This issue is also referenced in the [vuex next docs](https://next.vuex.vuejs.org/guide/getters.html):

> As of Vue 3.0, the getter’s result is not cached as the computed property does. This is a known issue that requires Vue 3.1 to be released.

Vue 3.1 and 3.2 were released since then, but that note wasn't ever updated.



Our use case:

We are migrating our app from vue^2.6.14 + vuex^3.6.2 to vue^3.2.26 + vuex^4.02.
Our app is making heavy use of vuex getters. We have literally thousands of lines of our app code in Vuex getters.
Many of those getters are executing CPU intensive operations.
While testing performance of the vue3 app version we found that vuex getters execute multiple times, despite their reactive dependencies are not changing (!) - this is not the case in vue2.6 where getters results get cached.
This behavior change causes a significant performance regression: the app is slower in tests. Such a performance regression is sufficient to hold back the update from the product’s performance perspective.

Any advice on what can we do to switch to Vue3 yet keep the performance as high as in Vue2.6?

**Comment by BoHuny** [comment] 2022-01-04 08:45
A solution we found was to replace the direct use of getters with a mapGetters to generate cached computed properties: https://next.vuex.vuejs.org/guide/getters.html#the-mapgetters-helper
(This is also considered good practice so it could be the occasion to refactor the sources, I guess)

**Comment by igal1c0de4n** [comment] 2022-01-04 14:56
@BoHuny the solution you mention is applicable for getters which are accessed from components, correct? 

In our case, there's an intricate getters interdependency within other vuex getters. So getter A depends on getter B which depends on getter C, etc. 

For this type of usage, cached computed properties add little value. That's because when getter A recomputes it forces many other computationally intensive getters to recompute. This is a clear regression from vue2.6(+vuex) where they are cached.

**Comment by BoHuny** [comment] 2022-01-05 08:10
@igal1c0de4n You're right, I didn't think about that particular use case
In that case if there's no other workaround it's clearly a regression from vuex3 as you mentioned

**Comment by thomasdao** [comment] 2022-01-10 10:38
I was also surprised to see that after a painful migration to Vue 3, the application became really slow because it uses Vuex getters heavily. The documentation says that this issue will be fixed when Vue 3.1 is released but even with the latest Vue 3.2.26 it is still not resolved.

**Comment by kyrsquir** [comment] 2022-01-14 07:43
@yyx990803 Could you please take a look at this?

**Comment by 8bitDesigner** [comment] 2022-01-25 05:52
Yep, `mapGetters` or referencing the store property via `computed` in your component is a good work around. I've been using this for the last few months without issue. For example:

``` vue
<script>
export default defineComponent({
  getters: {
    myStoreProperty () {
      return this.$store.getters.myStoreProperty
    }
  }
})
</script>
```

(or `computed(store.getters.myStoreProperty)` if you're using the composition API)

**Comment by leo-buneev** [comment] 2022-02-07 22:32
Here's another way to workaround without refactoring - moving getters to components completely:

before:
```
// store.js
export default {
  getters: {
    computedValue(state) {
      return complexComputation(state)
    }
  }
}
```

after: 
```
// store.js
import gettersCache from './gettersCache'
export default {
  getters: {
    computedValue() {
      return gettersCache.computedValue()
    }
  }
}

// gettersCache.js 
import { createApp } from 'vue'
import GettersCachingComponent from './GettersCachingComponent.vue'

const app = createApp(GettersCachingComponent)
export default app.mount('#gettersCachingApp')

// GettersCachingComponent.vue
<template>
  <div />
</template>

<script>
import $store from '@/store'

export default {
  computed: {
    computedValue() {
      const state = $store.state
      return complexComputation(state)
    }
  }
}
```

**Comment by bill-kasa** [comment] 2022-02-14 19:38
So, this is still an issue? Currently migration from Vue 2 and Vue 3 and this is concerning.

**Comment by igal1c0de4n** [comment] 2022-02-15 19:41
@leo-buneev the approach is interesting. 
I'm concerned about `computedValue` getting executed excessively. 
Sure, it's small however multiply by hundreds of getters in my app... it doesn't seem like the approach your want to take home and introduce to your parents.

Also, it requires refactoring hundreds (>1000) lines of code in my project.
I'm concerned after do all this work, I find out the performance is significantly worse than the 2.6 version.
Or that a new Vuex version fixes it, maybe it'll get solved "by design". Then I'll need to refactor my project back => wasted effort.

For now I'll be staying on 2.6 until the plan to address this issue become clearer

**Comment by fgarit-te** [comment] 2022-02-23 01:50
@bill-kasa still an issue as of vuex 4.0.2. Pretty critical issue, I might not have migrated my app to Vue 3 had I known about this. I also can't afford another migration to Pinia right now :/

**Comment by bill-kasa** [comment] 2022-02-23 04:01
> @bill-kasa still an issue as of vuex 4.0.2. Pretty critical issue, I might not have migrated my app to Vue 3 had I known about this. I also can't afford another migration to Pinia right now :/

Agreed. This seems like something that should be front-and-center on the Vue 3 Migration guide on the website.

**Comment by csicky** [comment] 2022-03-11 08:26
Is somebody working on fixing this? It seems Vue 2 is not upgradable after all, only for small apps and demos. 
I too have many getters depending on each other and I have also console logs in many of them. My surprise was so big when at first start of the project, after a very big work on migrating it, the console is flooded and settles only after long time.

**Comment by fgarit-te** [comment] 2022-03-11 17:19
Not entirely relevant, but to counter this problem, my team has started migrating to Pinia... Though Pinia is a clear upgrade from Vuex and the migration is pretty smooth (we're migrating modules one by one), fixing the tests is what takes us the most time. And we would have preferred doing this migration on our own terms instead of somewhat forced.

**Comment by csicky** [comment] 2022-03-11 17:55
Thank you for your suggestion, I will check it out.

**Comment by LifeIsStrange** [comment] 2022-03-11 21:11
Has anyone investigated wether Pinia cache getters results by default?

**Comment by fgarit-te** [comment] 2022-03-11 21:17
> Has anyone investigated wether Pinia cache getters results by default?

Yes, and they do.

**Comment by yyx990803** [comment] 2022-10-14 10:29
closed via https://github.com/vuejs/vuex/pull/1883 - will release patch soon.

**Closed by yyx990803** 2022-10-14 10:29 UTC
