### ISSUE TITLE
vue3 template ref   vuex => wrong reactive system

### ISSUE THREAD

**Issue by 12120290x1** [vuejs/vuex#1844] opened 2020-10-07 14:44 UTC
### Version
3.0.0

### Reproduction link
[https://github.com/12120290x1/error](https://github.com/12120290x1/error)

### Steps to reproduce
step1: click aaaa button
step2: click menu button

### What is expected?
tag nav have fixed-left-0 like this:

```html
<nav id="nav1" class="bg-primary fixed-left-0">
```

### What is actually happening?
this is actually happening:

```html
<nav id="nav1" class="bg-primary">
```

**Comment by posva** [comment] 2020-10-07 14:50
@12120290x1 transferred to the proper repository

**Comment by cuebit** [comment] 2020-10-09 15:50
This is all Vue is aware of during component instantiation:

```js
:class="{ 'nav1-open': $store.state.isNavOpen }"
```

Manipulating the classList works but the state is lost because Vue doesn't know about it. This is expected behaviour. If you're managing classes with Vue, you should manage them all through Vue as to track changes.

```js
setup() {
  const store = useStore()
  const isFixed = ref(false)

  const navClasses = computed(() => {
    return {
      'nav1-open': store.state.isNavOpen,
      'fixed-left-0': isFixed.value
    }
  })

  function addfix() {
    isFixed.value = true
  }

  return { addfix, navClasses }
}
```

```html
<nav ref="nav1" id="nav1" class="bg-primary" :class="navClasses">
```

For further questions, please consult the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/). 👍

**Closed by cuebit** 2020-10-09 15:50 UTC
