### ISSUE TITLE
Get module's namespace inside mutations/actions/getters...

### ISSUE THREAD

**Issue by SaekiRaku** [vuejs/vuex#1542] opened 2019-04-26 03:46 UTC
### What problem does this feature solve?

I have some mutations that need chain reaction in some cases, and for now, I have to hard code `namespace` inside the mutations. But I made this module as far as possible to reuse in other pages, and my project is not SPA, so I have to re-registerModule in every pages. But in some cases, I need to register the module for a different namespace to avoid conflict, and then it will cause error if I have to hard code `namespace` inside the mutations.

For example:
```javascript
function mutation(state, payload) {
    if(payload.situation){
        this.commit("Namespace/CommitFunction", { ... });
    }
    ...
    // Error: [vuex] unknown mutation type: Namespace/CommitFunction
}
```

It may also need to know the namespace in these situation:
* https://github.com/vuejs/vuex/issues/1244

### What does the proposed API look like?
```
function mutation(state, payload, namespace){
    ...
}
```

or

```
function mutation(state, payload){
    console.log(this.namespace);
}
```

**Comment by ktsn** [comment] 2019-04-26 04:36
You should not call `commit` in mutation... `this` in mutation is not meant to be used in userland.
And this is duplicate of #1244

**Closed by ktsn** 2019-04-26 04:36 UTC
