### ISSUE TITLE
Bug in vuex & vuex-router-sync: rawGetter is not a function

### ISSUE THREAD

**Issue by xiaocode** [vuejs/vuex#285] opened 2016-08-19 06:55 UTC
When click the route-link to another component, this error will show. I found it happen at vuex 2.0.0-rc.5 dist/index.js line 458 "store._wrappedGetters[**getterKey**]". When the getterKey is "default", this is an Object, not a Function. I don't know it is my problem or the bug.

**Comment by LinusBorg** [comment] 2016-08-19 07:19
Hello @xiaocode,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by LinusBorg** [comment] 2016-08-26 13:34
Closing for inactivity

**Comment by pelletiermaxime** [comment] 2016-09-12 17:47
Just ran into the same issue. Not sure I'm going to have the time to post an example anytime soon because my code isn't open source :/

**Comment by pelletiermaxime** [comment] 2016-09-12 18:10
Restarting my browser seems to have fixed the bug. Clearing the cache wasn't enough.

**Comment by codeofsumit** [comment] 2016-09-14 18:10
got the same issue

**Comment by pelletiermaxime** [comment] 2016-09-15 03:27
It seems to appear when I use the chrome devtools with the vue plugin. Everything works fine in Firefox.

**Comment by LinusBorg** [comment] 2016-09-15 07:25
Please provide exact versions (Vue, vue-router, vuex, vuex-router-sync), and if you cant reproduce it on jsfiddle, at least explain exctly *when* this error shows up. What are you doing in that moment?

**Comment by codeofsumit** [comment] 2016-09-15 08:34
I'll give it a shot.

vue 2.0.0-rc.5.
vue-router 2.0.0-rc.4
vuex 2.0.0-rc.5
vuex-router-sync 3.0.0

I found that in my case it shows up when I click on a specific component, here it's VLocationResults:
![image](https://cloud.githubusercontent.com/assets/2399810/18543392/e82b7d18-7b2f-11e6-82e3-1c8b981843d2.png)


The VLocationResults component looks like this:
```
import store from './../../store';

export default {
  mixins: [
  ],
  props: {
  },
  data() {
    return {
      loc: store, // <-- problem HERE
    };
  },
};
```

I'm assuming because `store` is some kind of circular structure or something. Removing that and assigning proper data like `store.state.dataProperty` makes everything work fine.

So I guess it's some wrong/invalid(?) data return that causes this.

I'm a total beginner in vue so I don't know if that is actually invalid.

**Comment by LinusBorg** [comment] 2016-09-15 13:41
Hi @codeofsumit 

Thanks for looking into this!

Yes, you should defnitely not add a vuex store to the local state of a component. If everything works fine for you when you don't do that, I would not consider this a bug.

So I'll hope that @pelletiermaxime can offer some additional insight.

**Comment by codeofsumit** [comment] 2016-09-15 13:57
@LinusBorg Of course I changed that property 😀
I did not know that this was not allowed. As I said I'm a total beginner and I thought the vue dev tools, or vue itself would tell me that I do something wrong instead throwing an error themselves.
Most other scenarios are handled with errors messages that help me find the problem.

**Comment by Async0x42** [comment] 2016-09-19 00:55
I'm having the rawGetter error as well, with Chrome and devtools. I only import the store for the main app, and in no other components, but if I keep devtools open while loading some routes, it always throws this rawGetter exception.

vuex-router-sync 3.0.0
vue-2.0.0-rc.6
vuex-2.0.0-rc.5

**Comment by ktsn** [comment] 2016-09-20 12:24
Hmm, I can't reproduce in my machine.
Can you guys provide the stack trace of the error?

**Comment by codeofsumit** [comment] 2016-09-20 12:41
![image](https://cloud.githubusercontent.com/assets/2399810/18670453/47f9d898-7f40-11e6-899d-184a89c27793.png)

**Comment by ktsn** [comment] 2016-09-21 14:58
@codeofsumit Thank you for providing the stack trace!
I can reproduce a similar error now, but it seems to happen only when we put the non-function value in `getters` object.
Are there any non-function value in your getters...? If not, do your getters run correctly?

**Comment by pelletiermaxime** [comment] 2016-09-23 17:14
Took me a while, but I think I fixed the error by changing my code from :

```
data () {
  return {
    decade: '2010',
  }
},

computed: {
  teamList () {
    if (store.state.hof.all[this.decade] === undefined) {
      return []
    }
    return store.state.hof.all[this.decade].teams
  },
}
```

to :

```
data () {
  return {
    decade: '2010',
  }
},

computed: {
  hofDecade () {
    return store.state.hof.all[this.decade] || {teams: []}
  },
  teamList () {
    return this.hofDecade.teams
  },
}
```

I'm not sure I understand the difference or why it worked just fine if the chrome dev tools are not open.

**Comment by chenEdgar** [comment] 2017-03-16 09:19
I've got the error just moment. and the reason is if store contains a blank gutter.js, the error will recurrence

**Comment by ktsn** [comment] 2017-03-20 14:08
Hi, I'm reinvestigate this issue and I noticed there could be a problem if we hot reload getters. Is this error occurred after hot reloading? If so, how is your code of hot reloading looks like?
Thanks for your kind collaboration!

**Comment by joemanfoo** [comment] 2017-03-22 13:15
@chenEdgar's comment is spot on for me, blank getter.js file and nothing being assigned to getters: getters
```
export default new Vuex.Store({
  strict: false,
  // actions, // commented out since I've gone module route
  // getters,  // commented out since I've gone module route
  modules: {
    crop, shop, pending, styles, user
  }
})
```

**Comment by ktsn** [comment] 2017-03-22 14:10
@chenEdgar @joemanfoo 
Do you use babel to transpile your js code and also convert ESModule syntax with it?
If that is the case, it seems that wildcard import (`import * as getters from '...'`) will add `default` field in `getters` and it causes this error.

I don't think this is a Vuex bug but we can improve it by adding assertions for getters to let the users know what happens in it. I'll make a PR for it.

**Comment by joemanfoo** [comment] 2017-03-22 16:29
@ktsn - Yes on the transpile and yes on the wildcard import.  The interesting thing is I think this was only reported in Chrome, firefox didn't produce the same error message.  Anyhow, the advice to remove empty getters fixed the problem and totally agree that an assertion to let users know what's happening is perfect!

**Comment by ktsn** [comment] 2017-03-23 03:32
> this was only reported in Chrome, firefox didn't produce the same error message

It seems like vue-devtools triggers all getters for snapshot so the error is occurred.

Finally found the root cause 😂

**Closed** 2017-05-15 02:35 UTC
Labels: 2.0, enhancement
