### ISSUE TITLE
mapState not working with namespaced?

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vuex#565] opened 2017-01-04 11:52 UTC
Hi all,
Vue: 2.1.8
Vuex: 2.1.1

In `computed` hook I cannot get object current correct.

working
```
 ...mapGetters('pages/contact', ['subjects'])
``` 

working
```
computed: {
  subjects() {
    return this.$store.state.pages.contact.subjects
  }
 }
```
-------
**NOT working**
```
...mapState('pages/contact', {
  subjects: state => state
})
```

**Comment by LinusBorg** [comment] 2017-01-04 12:23
Hello @tronghiep92,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.

**Comment by ktsn** [comment] 2017-01-04 14:17
If "NOT working" means the 1st argument is not the latest state, it is already fixed via #528

**Comment by ktsn** [comment] 2017-01-10 00:36
Closing for inactivity. If the issue is not same as #528, please open a new issue with providing further information/reproduction.

**Closed by ktsn** 2017-01-10 00:36 UTC
Labels: need repro

**Comment by LeCoupa** [comment] 2017-07-25 14:01
@ktsn I still struggle with the same issue. How can I get the latest state?

    computed: mapState({
        formData: state => { return state.main.form.data },
    })

**Comment by ktsn** [comment] 2017-07-25 14:56
Thanks for reporting. Please open a new issue with a reproduction 🙂
