### ISSUE TITLE
Component being detached incorrectly

### ISSUE THREAD

**Issue by asethwright** [vuejs/vuex#442] opened 2016-11-04 13:36 UTC
Hi, I asked this on the forum and didn't get any answer. I'm not sure if this is the intended behavior and I'm doing something wrong, so I apologize ahead of time.

Vuex 2 seems to be merging my data instead of overwriting the object in my mutation. In 1.0 this worked fine.

```javascript
  [PREROLL_START](state, i) {
    console.log(i);
    state.player.prerolling = true;
    state.player.loaded = false;
    state.navigation.queued = state.navigation.item;
    state.navigation.item = {
      align: 'left',
      background: 'gold',
      label: 'Test',
      headline: 'Test',
      hyperlink: '#',
      text: 'Here is my text.',
      type: 'text',
      skip: 1,
      timer: 10000,
    };
    console.log(state.navigation.item); // object above, merged with the original state.navigation.item
    // newer object properties contain getter/setters. old object properties are static props.
  },
```

**Comment by asethwright** [comment] 2016-11-04 13:45
Sorry, I should also note that 

```javascript
 [PREROLL_START](state, i) {
    console.log(i); //same as the log statement at the bottom, after opening in the console
    state.player.prerolling = true;
    state.player.loaded = false;
    state.navigation.queued = state.navigation.item;
    state.navigation.item = state.navigation.queued.pre;
    console.log(state.navigation.item);
  },
```

**Comment by asethwright** [comment] 2016-11-04 13:55
I think this has to do with how quickly the DOM is being evaluated. I am pretty sure this is my fault, but would really appreciate if someone could explain what might be happening.

**Comment by asethwright** [comment] 2016-11-04 14:57
OK actually one of my components is being removed incorrectly. I never touch activeItem. In fact, the getter is never reevaluated.

```javascript
    <player-video
      v-if="(activeItem && activeItemType === 'video') || playlistVideoShim"
      v-show="playerIsLoaded"
    ></player-video>
```

```javascript
// vuex getters
export const activeItem = (state) => {
  console.log(JSON.stringify(state.navigation.item)); //never logged
  return state.navigation.item;
};

export const activeItemType = (state) => {
  console.log(JSON.stringify(state.navigation.item)); //never logged

  if (!state.navigation.item) {
    return false;
  }

  if (state.navigation.item.type === 'video') {
    const sources = JSON.parse(state.navigation.item.text);
    if (sources.youtube !== '') {
      return 'youtube';
    }
    return 'custom';
  }
```

```javascript
// in component
      if (this.activeItem.pre
        && !this.bumperPrerolling
        && !this.activePlaylist) {
        console.log('Video -> Preroll start.');
        this.prerollStart();
        console.log(JSON.stringify(this.activeItem)); // correct
        return false;
      }
```

```javascript
// mutation
  [PREROLL_START](state) {
    state.player.prerolling = true;
    state.player.loaded = false;
    state.navigation.roll = state.navigation.item.pre;
    // not modifying activeItem (or state.navigation.item) at all now
  },
```

logs show...

Video -> Preroll start.
** stringified object activeItem, correct **
Video.vue?d623:174 Video -> Detaching player.

**Comment by asethwright** [comment] 2016-11-04 15:14
Also the <player-video></player-video> reattaches immediately after detach, with no reevaluation of the getters and no logs.

Video -> Detaching player.
Video.vue?18d3:184 Video -> Clearing start timer.
Video.vue?18d3:374 Video -> Removing event listeners.
Video -> Attaching player.
Video.vue?18d3:223 Video -> Adding event listeners.
Video.vue?18d3:237 Video -> start load.

**Comment by LinusBorg** [comment] 2016-11-04 15:15
Hi.

1. Can I get a link to your forum post? This is almost cewrtainly not a bug and theregfore does not belong here
2. I don't really understand what the prolbem is, first the object is somehow "merged", then later you say it's correct, then you say the getter never is called, although it must have been called if it logs this:
```js
if (this.activeItem.pre
        && !this.bumperPrerolling
        && !this.activePlaylist) {
        console.log('Video -> Preroll start.');
```

So... your no idea how to help you so far.

**Closed by LinusBorg** 2016-11-04 15:15 UTC

**Comment by asethwright** [comment] 2016-11-04 15:22
I posted on a chat, not a forum. So I apologize if that wasn't the correct avenue.

My component is being removed and then re mounted without evaluating my getter, which makes no sense.

My v-if statement is always evaluating to true, so there shouldn't be any change to the DOM. Perhaps this is not an issue with Vuex and instead Vue 2 itself.
