### ISSUE TITLE
mapGetters use "this" in unbound function definition

### ISSUE THREAD

**Issue by Fuzzyma** [vuejs/vuex#1822] opened 2020-08-31 02:57 UTC
### Version
4.0.0-beta.4

### Reproduction link
[https://github.com/vuejs/vuex/blob/83bc26fe55417692f386db9b76634eb58794282e/src/helpers.js#L81](https://github.com/vuejs/vuex/blob/83bc26fe55417692f386db9b76634eb58794282e/src/helpers.js#L81)

### Steps to reproduce
The code uses `this` in the specified line and in next lines in a classic function definition and is therefore not what is expected here.

### What is expected?
Good question. An arrow function does not solve the problem since the function in a whole is unbound. However, it would atleast enable us to use `mapGetters.call(ctc.root.$store, ...)` in the setup function. Atm it doesnt work at all

### What is actually happening?
An error is thrown because `this.$store` is undefined

**Comment by kiaking** [comment] 2020-08-31 09:47
Yes, this is expected, `mapXXX` helpers does not work in `setup` hook, and we're planning to implement `useXXX` helpers for the `setup` hook 👍 I'll be closing this one since we have an issue for that already.

**Closed by kiaking** 2020-08-31 09:47 UTC

**Comment by Fuzzyma** [comment] 2020-08-31 10:28
@kiaking this is not about the setup function. This method won't work in other contexts, too. Simply because `this` will never pint to the right object like this

**Comment by kiaking** [comment] 2020-08-31 11:27
Not sure what is happening here, the line was there 4 years ago and never changed since. Could you create reproduction code that illustrate the problem you're having?

**Comment by cuebit** [comment] 2020-08-31 11:27
The mapXXX helpers are composable functions bound to a Vue instance. Since a store binding exists in a Vue instance, `this` context makes absolute sense. 

Your expectation is that the helpers allow mapping from a store instance, which is not the case and not the intended behaviour. 

```js
// Won't work
mapGetters.call(ctc.root.$store, ...)

// Will work
mapGetters.call(ctc.root, ...)
```

**Comment by cuebit** [comment] 2020-08-31 11:56
The `mapXXX` helpers were not designed to receive a context, rather they are to be bound to a Vue instance and receive their context when the instance is created.

Your expectation is the very description of a typical `useXXX` composable which @kiaking acknowledges will be implemented in the near future.

**Comment by Fuzzyma** [comment] 2020-08-31 13:00
Oh yes, I now see it. I indeed was way off here. Shame on me. So, all functions returned by mapGetters are actually bound to the vue instance. That makes total sense. I had a weird brain lag.

So even if this is not intended to do, you technically can do this:

```js
const getters = Vuex.mapGetters(['some', 'getters']).map(g => g.bind(ctx.root))
```

**Comment by cuebit** [comment] 2020-08-31 13:02
> So even if this is not intended to do, you technically can do this:
> 
> 
> 
> ```js
> 
> const getters = Vuex.mapGetters(['some', 'getters']).map(g => g.bind(ctx.root))
> 
> ```

Nailed it 👍
