### ISSUE TITLE
any good idea for us to express editable list using vuex?

### ISSUE THREAD

**Issue by rawbin-** [vuejs/vuex#1171] opened 2018-03-05 16:16 UTC
### Version
2.3.0

### Reproduction link
[https://codesandbox.io/s/38n8j41vzq](https://codesandbox.io/s/38n8j41vzq)

### Steps to reproduce
just open the page

### What is expected?
any good way to bind form using vuex especially when there are many form item to bind

### What is actually happening?
for every form item we do like this 

```
<input v-model="message">
// ...
computed: {
  message: {
    get () {
      return this.$store.state.myModule.message
    },
    set (value) {
      this.$store.commit('updateMessage', value)
    }
  }
}
```
in case that we use an module to express an data structure,it turns out 

```
<input v-model="message">
// ...
computed: {
  message: {
    get () {
      return this.$store.state.myModule.someObj.message
    },
    set (value) {
      this.$store.commit('updateMessage', value)
    }
  },
 phone: {
    get () {
      return this.$store.state.myModule.someObj.phone
    },
    set (value) {
      this.$store.commit('updatePhone', value)
    }
  }
}
}
```
it's boring to do this on every form item when there is much more to do

**Comment by rawbin-** [comment] 2018-03-05 16:19
It's not a good idea to bind form item with the doc for vuex on every item, we write too much alike code .

**Comment by LinusBorg** [comment] 2018-03-06 07:54
1. This is a support question, not a bug or a feature, so I will close this issue and refer you to forum.vuejsorg / chat.vuejs.org
2. It's not hard to write a small mixin that generates these computed props for you

**Closed by LinusBorg** 2018-03-06 07:54 UTC

**Comment by rawbin-** [comment] 2018-03-06 12:54
@LinusBorg  thanks for your mixin, I got it
