### ISSUE TITLE
this is undefined in vuex

### ISSUE THREAD

**Issue by silentmissile** [vuejs/vuex#1411] opened 2018-10-01 01:58 UTC
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/7jqyyvmqm1](https://codesandbox.io/s/7jqyyvmqm1)

### Steps to reproduce
win10 x64
nodejs 10.11.0 x64
@vue/cli 3.0.4
@vue/cli-service 3.0.4
@vue/cli-service-global 3.0.4
vue 2.5.17
vue-router 3.0.1

<template>
  <div>
    <router-view></router-view>
  </div>
</template>

<script>
import Initial from './Initial'
export default {
  components: {
    'initial': Initial,
  },
  data () {
    return {
    }
  },
  methods: {
  },
  created () {
    console.log(this.$store)
    this.$store.dispatch('Init')
  }
}
</script>

<style scoped>

</style>

when running
npm run serve
the service runs smoothly

when I visit this component in browser, some error in console

this.$store can be recognized and logged correctly, but

[Vue warn]: Error in created hook: "TypeError: this is undefined"

found in

---> <Design> at src/views/initial.vue
       <Entrance> at src/Entrance.vue
         <Root>

### What is expected?
fix this bug

### What is actually happening?
this is undefined if vuex

---
in codesandbox, it can't be reproduced, maybe it's caused by conflict of some other software like nodejs

**Comment by zenbaku** [comment] 2018-10-01 03:45
It seems some files, like `src/Entrance.vue` and `views/initial.vue` are missing from the sandbox. Maybe adding those might help with reproducing the bug?

**Comment by ktsn** [comment] 2018-10-01 05:06
> in codesandbox, it can't be reproduced, maybe it's caused by conflict of some other software like nodejs

Could you make an example project as a reproduction as GitHub repository, then? We cannot do anything if you cannot reproduce the problem.

**Comment by ktsn** [comment] 2018-10-08 15:12
Closing until a reproduction is provided.

**Closed by ktsn** 2018-10-08 15:12 UTC
Labels: need repro
