### ISSUE TITLE
vuex@2.0 getters not registered within dynamic nested modules

### ISSUE THREAD

**Issue by karol-f** [vuejs/vuex#248] opened 2016-07-12 09:50 UTC
Reading `v2.0.0-rc.1` release notes we can see that **getters** should be available inside dynamically registered modules:
> Nested Modules Improvements
Actions, getters and mutations are all supported inside modules.

But when looking in `index.js` source code, into dynamic module registration (`module()` method) I can see that **getters** are not propagated:

`
const {
      state,
      actions,
      mutations,
      modules
    } = module
`
### Desired behaviour
Dynamically registered module getters should be available.

### Current behaviour
http://www.webpackbin.com/E1JVbppL-

I define getters in two ways:
* in `store.js` using `getters: {
    rootState: (state) => state
  }` (when store initializes)
* in `widget.js` using `getters: {
        moduleState : (state) => state
      }` (dynamic module registration, using `store.module(...)`)

As you can see in output `this.$store.getters.moduleState` is empty.

Tested in
* v2.0.0-rc.1
* v2.0.0-rc.3

**Comment by LinusBorg** [comment] 2016-07-12 10:45
Have you actually tried it? Because 
1. it works, and 
2. you were looking in the wrong place:

https://github.com/vuejs/vuex/blob/next/src/index.js#L267-L283

**Comment by LinusBorg** [comment] 2016-07-12 10:51
Hello @karol-f ,

thanks for filing this issue.

I'm not sure what you think the issue is. You say you tested von versions. What was the expected result, and what was actually happening? Can you reprocude the problem in a fiddle?

Because what you quoted just means that you can *define* getters in modules, and that woprks perfectly well.

Getters are also collected from all submodules and wrapped accordingly - it just happens in another place than where you seemed to be looking, namely here:

https://github.com/vuejs/vuex/blob/next/src/index.js#L38

But maybe I missunderstand what your issue is about - can you elaborate?

**Comment by karol-f** [comment] 2016-07-12 11:31
Hi @LinusBorg  - sorry for not providing link with problematic code. Here it is:
http://www.webpackbin.com/E1JVbppL-

As you can see you can define getters in two ways:
* in `store.js` by `getters: {
    rootState: (state) => state
  }`
* in `widget.js` by `getters: {
        moduleState : (state) => state
      }`

As you can see in output `this.$store.getters.moduleState` is empty.

Sorry for confusion and not providing link in a first place, regards!

**Comment by LinusBorg** [comment] 2016-07-12 12:33
Okay, now I see the issue. Thanks for the demo, we will look into it.

**Comment by LinusBorg** [comment] 2016-07-12 12:44
@karol-f Could you edit your initial post to include the demo link?

**Comment by karol-f** [comment] 2016-07-12 12:46
@LinusBorg Done

**Comment by analog-nico** [comment] 2016-07-14 22:54
The code to register the `getters` is just missing in `store.module(...)` as @karol-f points out.

`store.module(...)` needs something like the `initStoreState(...)` call that is used the [constructor](https://github.com/vuejs/vuex/blob/next/src/index.js#L38-L39).

**Comment by LinusBorg** [comment] 2016-07-15 09:29
It's not just missing, though.

When initializing the store, first getters are collected from all modules, then the `module()` method is called to recursively add state, actions and mutations from all modules.

So the code is there, it would have to be moved into `module()`, which is not a simple copy/paste job ;)

But we will get on it.

**Comment by ktsn** [comment] 2016-07-22 00:23
It's fixed on #253

**Comment by LinusBorg** [comment] 2016-07-22 09:18
Thanks @ktsn !!

**Closed** 2016-07-22 09:17 UTC
Labels: bug
